# Generated by Django 4.1.1 on 2022-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.BigIntegerField(unique=True, verbose_name='External ID')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price USD')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price RUB')),
                ('delivery_dt', models.DateField(verbose_name='Delivery date')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_dt'],
            },
        ),
    ]
